// Référentiel des notions du programme CFA Niveau I : une notion = un
// Learning Module (LM), 93 en tout. C'est l'unité que partagent les
// chapitres des cours audio (?module=N), les types de calcul (source « LM 8 · … »),
// les pages de fiche et les numéros de reading de la banque de questions.
// Module neutre (pas de "use client").
//
// FICHIER GÉNÉRÉ par scripts/notions/build.mjs : ne pas le modifier à la main.
// Les libellés courts et les numéros de reading se changent dans
// scripts/notions/referentiel.mjs, puis on relance le générateur.
//
// Deux numérotations des readings circulent dans le contenu : « banque »
// (banque de practice exams, titres « … — QCM (R59–R61) », commentaires des
// drills) et « schweser » (livres Schweser, anciens titres Fixed Income
// « (R47–R51) »). Les deux vont de 1 à 93 et se chevauchent.

export type Numerotation = "banque" | "schweser";

export type Notion = {
  /** « fixed_income:11 » : clé de matière (lib/practiceTopics.ts) et n° du LM */
  id: string;
  matiere: string;
  /** n° du LM dans la matière = n° du chapitre audio */
  lm: number;
  /** titre officiel anglais (chapitre de lib/courses.ts) */
  titre: string;
  /** libellé court français, celui que lit le joueur */
  court: string;
  readings: Record<Numerotation, number>;
  /** sous-parties de la banque (Guidance for Standards I–VII), qui servent de concept */
  sousParties?: { reading: string; libelle: string }[];
  /** chapitre du cours audio */
  cours: string;
  /** types de calcul rattachés */
  calculs: { cle: string; nom: string; href: string }[];
  /** pages de fiche où la notion est travaillée, la plus pertinente d'abord (page null : ancre d'une fiche d'un seul tenant) */
  fiches: { href: string; page: number | null }[];
  /** titres des paquets de flashcards qui la couvrent */
  flashcards: string[];
};

export const NOTIONS: Notion[] = [
  {
    id: "ethics:1",
    matiere: "ethics",
    lm: 1,
    titre: "Ethics and Trust in the Investment Profession",
    court: "Éthique et confiance",
    readings: { banque: 89, schweser: 89 },
    cours: "/courses/ethics?module=1",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "ethics:2",
    matiere: "ethics",
    lm: 2,
    titre: "Code of Ethics and Standards of Professional Conduct",
    court: "Code et Standards",
    readings: { banque: 90, schweser: 90 },
    cours: "/courses/ethics?module=2",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "ethics:3",
    matiere: "ethics",
    lm: 3,
    titre: "Guidance for Standards I–VII",
    court: "Standards I à VII",
    readings: { banque: 91, schweser: 91 },
    sousParties: [
      { reading: "91.1", libelle: "Standards I(A) et I(B)" },
      { reading: "91.2", libelle: "Standards I(C) et I(D)" },
      { reading: "91.3", libelle: "Standard II" },
      { reading: "91.4", libelle: "Standards III(A) et III(B)" },
      { reading: "91.5", libelle: "Standards III(C), III(D) et III(E)" },
      { reading: "91.6", libelle: "Standard IV" },
      { reading: "91.7", libelle: "Standard V" },
      { reading: "91.8", libelle: "Standard VI" },
      { reading: "91.9", libelle: "Standard VII" },
    ],
    cours: "/courses/ethics?module=3",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "ethics:4",
    matiere: "ethics",
    lm: 4,
    titre: "Introduction to the Global Investment Performance Standards (GIPS)",
    court: "GIPS",
    readings: { banque: 92, schweser: 92 },
    cours: "/courses/ethics?module=4",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "ethics:5",
    matiere: "ethics",
    lm: 5,
    titre: "Ethics Application",
    court: "Cas d'éthique",
    readings: { banque: 93, schweser: 93 },
    cours: "/courses/ethics?module=5",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:1",
    matiere: "quant",
    lm: 1,
    titre: "Rates and Returns",
    court: "Taux et rendements",
    readings: { banque: 1, schweser: 1 },
    cours: "/courses/quantitative-methods?module=1",
    calculs: [
      {
        cle: "return-measures",
        nom: "Mesures de rendement (HPR, moyennes, annualisation, réel)",
        href: "/calculs/portfolio-management/return-measures",
      },
      {
        cle: "mwr-twr",
        nom: "Money-weighted vs time-weighted return",
        href: "/calculs/portfolio-management/mwr-twr",
      },
    ],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:2",
    matiere: "quant",
    lm: 2,
    titre: "Time Value of Money in Finance",
    court: "Valeur temps de l'argent",
    readings: { banque: 2, schweser: 2 },
    cours: "/courses/quantitative-methods?module=2",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:3",
    matiere: "quant",
    lm: 3,
    titre: "Statistical Measures of Asset Returns",
    court: "Statistiques des rendements",
    readings: { banque: 3, schweser: 3 },
    cours: "/courses/quantitative-methods?module=3",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:4",
    matiere: "quant",
    lm: 4,
    titre: "Probability Trees and Conditional Expectations",
    court: "Arbres de probabilités",
    readings: { banque: 4, schweser: 4 },
    cours: "/courses/quantitative-methods?module=4",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:5",
    matiere: "quant",
    lm: 5,
    titre: "Portfolio Mathematics",
    court: "Mathématiques du portefeuille",
    readings: { banque: 5, schweser: 5 },
    cours: "/courses/quantitative-methods?module=5",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:6",
    matiere: "quant",
    lm: 6,
    titre: "Simulation Methods",
    court: "Simulation",
    readings: { banque: 6, schweser: 6 },
    cours: "/courses/quantitative-methods?module=6",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:7",
    matiere: "quant",
    lm: 7,
    titre: "Estimation and Inference",
    court: "Estimation et inférence",
    readings: { banque: 7, schweser: 7 },
    cours: "/courses/quantitative-methods?module=7",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:8",
    matiere: "quant",
    lm: 8,
    titre: "Hypothesis Testing",
    court: "Tests d'hypothèse",
    readings: { banque: 8, schweser: 8 },
    cours: "/courses/quantitative-methods?module=8",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:9",
    matiere: "quant",
    lm: 9,
    titre: "Parametric and Non-Parametric Tests of Independence",
    court: "Tests d'indépendance",
    readings: { banque: 9, schweser: 9 },
    cours: "/courses/quantitative-methods?module=9",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:10",
    matiere: "quant",
    lm: 10,
    titre: "Simple Linear Regression",
    court: "Régression linéaire",
    readings: { banque: 10, schweser: 10 },
    cours: "/courses/quantitative-methods?module=10",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "quant:11",
    matiere: "quant",
    lm: 11,
    titre: "Introduction to Big Data Techniques",
    court: "Big data et fintech",
    readings: { banque: 11, schweser: 11 },
    cours: "/courses/quantitative-methods?module=11",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:1",
    matiere: "economics",
    lm: 1,
    titre: "The Firm and Market Structures",
    court: "Structures de marché",
    readings: { banque: 12, schweser: 12 },
    cours: "/courses/economics?module=1",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:2",
    matiere: "economics",
    lm: 2,
    titre: "Understanding Business Cycles",
    court: "Cycles économiques",
    readings: { banque: 13, schweser: 13 },
    cours: "/courses/economics?module=2",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:3",
    matiere: "economics",
    lm: 3,
    titre: "Fiscal Policy",
    court: "Politique budgétaire",
    readings: { banque: 14, schweser: 14 },
    cours: "/courses/economics?module=3",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:4",
    matiere: "economics",
    lm: 4,
    titre: "Monetary Policy",
    court: "Politique monétaire",
    readings: { banque: 15, schweser: 15 },
    cours: "/courses/economics?module=4",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:5",
    matiere: "economics",
    lm: 5,
    titre: "Introduction to Geopolitics",
    court: "Géopolitique",
    readings: { banque: 16, schweser: 16 },
    cours: "/courses/economics?module=5",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:6",
    matiere: "economics",
    lm: 6,
    titre: "International Trade",
    court: "Commerce international",
    readings: { banque: 17, schweser: 17 },
    cours: "/courses/economics?module=6",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:7",
    matiere: "economics",
    lm: 7,
    titre: "Capital Flows and the FX Market",
    court: "Flux de capitaux et change",
    readings: { banque: 18, schweser: 18 },
    cours: "/courses/economics?module=7",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "economics:8",
    matiere: "economics",
    lm: 8,
    titre: "Exchange Rate Calculations",
    court: "Calculs de change",
    readings: { banque: 19, schweser: 19 },
    cours: "/courses/economics?module=8",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:1",
    matiere: "corporate",
    lm: 1,
    titre: "Organizational Forms, Corporate Issuer Features, and Ownership",
    court: "Formes d'entreprise",
    readings: { banque: 22, schweser: 20 },
    cours: "/courses/corporate-issuers?module=1",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:2",
    matiere: "corporate",
    lm: 2,
    titre: "Investors and Other Stakeholders",
    court: "Parties prenantes",
    readings: { banque: 23, schweser: 21 },
    cours: "/courses/corporate-issuers?module=2",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:3",
    matiere: "corporate",
    lm: 3,
    titre: "Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits",
    court: "Gouvernance",
    readings: { banque: 24, schweser: 22 },
    cours: "/courses/corporate-issuers?module=3",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:4",
    matiere: "corporate",
    lm: 4,
    titre: "Working Capital and Liquidity",
    court: "Fonds de roulement et liquidité",
    readings: { banque: 25, schweser: 23 },
    cours: "/courses/corporate-issuers?module=4",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:5",
    matiere: "corporate",
    lm: 5,
    titre: "Capital Investments and Capital Allocation",
    court: "Investissements et allocation du capital",
    readings: { banque: 26, schweser: 24 },
    cours: "/courses/corporate-issuers?module=5",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:6",
    matiere: "corporate",
    lm: 6,
    titre: "Capital Structure",
    court: "Structure du capital",
    readings: { banque: 27, schweser: 25 },
    cours: "/courses/corporate-issuers?module=6",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "corporate:7",
    matiere: "corporate",
    lm: 7,
    titre: "Business Models",
    court: "Modèles d'affaires",
    readings: { banque: 28, schweser: 26 },
    cours: "/courses/corporate-issuers?module=7",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "fsa:1",
    matiere: "fsa",
    lm: 1,
    titre: "Introduction to Financial Statement Analysis",
    court: "Cadre de l'analyse financière",
    readings: { banque: 29, schweser: 27 },
    cours: "/courses/financial-statement-analysis?module=1",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=1", page: 1 }],
    flashcards: ["Financial Statement Analysis — Flashcards 1/4 (Cadre d'analyse, résultat & bilan)"],
  },
  {
    id: "fsa:2",
    matiere: "fsa",
    lm: 2,
    titre: "Analyzing Income Statements",
    court: "Compte de résultat",
    readings: { banque: 30, schweser: 28 },
    cours: "/courses/financial-statement-analysis?module=2",
    calculs: [],
    fiches: [],
    flashcards: ["Financial Statement Analysis — Flashcards 1/4 (Cadre d'analyse, résultat & bilan)"],
  },
  {
    id: "fsa:3",
    matiere: "fsa",
    lm: 3,
    titre: "Analyzing Balance Sheets",
    court: "Bilan",
    readings: { banque: 31, schweser: 29 },
    cours: "/courses/financial-statement-analysis?module=3",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=2", page: 2 }],
    flashcards: ["Financial Statement Analysis — Flashcards 1/4 (Cadre d'analyse, résultat & bilan)"],
  },
  {
    id: "fsa:4",
    matiere: "fsa",
    lm: 4,
    titre: "Analyzing Statements of Cash Flows I",
    court: "Tableau des flux I",
    readings: { banque: 32, schweser: 30 },
    cours: "/courses/financial-statement-analysis?module=4",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=3", page: 3 }],
    flashcards: ["Financial Statement Analysis — Flashcards 2/4 (Flux de trésorerie & stocks)"],
  },
  {
    id: "fsa:5",
    matiere: "fsa",
    lm: 5,
    titre: "Analyzing Statements of Cash Flows II",
    court: "Tableau des flux II",
    readings: { banque: 33, schweser: 31 },
    cours: "/courses/financial-statement-analysis?module=5",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=4", page: 4 }],
    flashcards: ["Financial Statement Analysis — Flashcards 2/4 (Flux de trésorerie & stocks)"],
  },
  {
    id: "fsa:6",
    matiere: "fsa",
    lm: 6,
    titre: "Analysis of Inventories",
    court: "Stocks",
    readings: { banque: 34, schweser: 32 },
    cours: "/courses/financial-statement-analysis?module=6",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=5", page: 5 }],
    flashcards: ["Financial Statement Analysis — Flashcards 2/4 (Flux de trésorerie & stocks)"],
  },
  {
    id: "fsa:7",
    matiere: "fsa",
    lm: 7,
    titre: "Analysis of Long-Term Assets",
    court: "Actifs long terme",
    readings: { banque: 35, schweser: 33 },
    cours: "/courses/financial-statement-analysis?module=7",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=6", page: 6 }],
    flashcards: ["Financial Statement Analysis — Flashcards 3/4 (Actifs & passifs long terme, impôts)"],
  },
  {
    id: "fsa:8",
    matiere: "fsa",
    lm: 8,
    titre: "Topics in Long-Term Liabilities and Equity",
    court: "Passifs long terme et capitaux propres",
    readings: { banque: 36, schweser: 34 },
    cours: "/courses/financial-statement-analysis?module=8",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=7", page: 7 }],
    flashcards: ["Financial Statement Analysis — Flashcards 3/4 (Actifs & passifs long terme, impôts)"],
  },
  {
    id: "fsa:9",
    matiere: "fsa",
    lm: 9,
    titre: "Analysis of Income Taxes",
    court: "Impôts sur le résultat",
    readings: { banque: 37, schweser: 35 },
    cours: "/courses/financial-statement-analysis?module=9",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=8", page: 8 }],
    flashcards: ["Financial Statement Analysis — Flashcards 3/4 (Actifs & passifs long terme, impôts)"],
  },
  {
    id: "fsa:10",
    matiere: "fsa",
    lm: 10,
    titre: "Financial Reporting Quality",
    court: "Qualité de l'information",
    readings: { banque: 38, schweser: 36 },
    cours: "/courses/financial-statement-analysis?module=10",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=9", page: 9 }],
    flashcards: [
      "Financial Statement Analysis — Flashcards 4/4 (Qualité de l'information, techniques & modélisation)",
    ],
  },
  {
    id: "fsa:11",
    matiere: "fsa",
    lm: 11,
    titre: "Financial Analysis Techniques",
    court: "Ratios financiers",
    readings: { banque: 39, schweser: 37 },
    cours: "/courses/financial-statement-analysis?module=11",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=10", page: 10 }],
    flashcards: [
      "Financial Statement Analysis — Flashcards 4/4 (Qualité de l'information, techniques & modélisation)",
    ],
  },
  {
    id: "fsa:12",
    matiere: "fsa",
    lm: 12,
    titre: "Introduction to Financial Statement Modeling",
    court: "Modélisation financière",
    readings: { banque: 40, schweser: 38 },
    cours: "/courses/financial-statement-analysis?module=12",
    calculs: [],
    fiches: [{ href: "/fiches/financial-statement-analysis?page=11", page: 11 }],
    flashcards: [
      "Financial Statement Analysis — Flashcards 4/4 (Qualité de l'information, techniques & modélisation)",
    ],
  },
  {
    id: "equity:1",
    matiere: "equity",
    lm: 1,
    titre: "Market Organization and Structure",
    court: "Organisation des marchés",
    readings: { banque: 41, schweser: 39 },
    cours: "/courses/equity?module=1",
    calculs: [
      {
        cle: "margin-purchase",
        nom: "Achat sur marge (margin transaction)",
        href: "/calculs/equity/margin-purchase",
      },
      {
        cle: "short-sale",
        nom: "Vente à découvert (short sale)",
        href: "/calculs/equity/short-sale",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=1", page: 1 }],
    flashcards: [],
  },
  {
    id: "equity:2",
    matiere: "equity",
    lm: 2,
    titre: "Security Market Indexes",
    court: "Indices boursiers",
    readings: { banque: 42, schweser: 40 },
    cours: "/courses/equity?module=2",
    calculs: [
      {
        cle: "index-weighting",
        nom: "Méthodes de pondération d'indice (index weighting)",
        href: "/calculs/equity/index-weighting",
      },
      {
        cle: "index-returns",
        nom: "Price return et total return d'un indice",
        href: "/calculs/equity/index-returns",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=2", page: 2 }],
    flashcards: [],
  },
  {
    id: "equity:3",
    matiere: "equity",
    lm: 3,
    titre: "Market Efficiency",
    court: "Efficience des marchés",
    readings: { banque: 43, schweser: 41 },
    cours: "/courses/equity?module=3",
    calculs: [],
    fiches: [{ href: "/fiches/equity?page=3", page: 3 }],
    flashcards: [],
  },
  {
    id: "equity:4",
    matiere: "equity",
    lm: 4,
    titre: "Overview of Equity Securities",
    court: "Titres de capital",
    readings: { banque: 44, schweser: 42 },
    cours: "/courses/equity?module=4",
    calculs: [
      {
        cle: "roe-book-value",
        nom: "ROE, valeur comptable et price-to-book",
        href: "/calculs/equity/roe-book-value",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=4", page: 4 }],
    flashcards: [],
  },
  {
    id: "equity:5",
    matiere: "equity",
    lm: 5,
    titre: "Company Analysis: Past and Present",
    court: "Analyse d'entreprise",
    readings: { banque: 45, schweser: 43 },
    cours: "/courses/equity?module=5",
    calculs: [
      {
        cle: "operating-leverage",
        nom: "Levier opérationnel et financier (DOL, DFL)",
        href: "/calculs/equity/operating-leverage",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=5", page: 5 }],
    flashcards: [],
  },
  {
    id: "equity:6",
    matiere: "equity",
    lm: 6,
    titre: "Industry and Competitive Analysis",
    court: "Analyse sectorielle",
    readings: { banque: 46, schweser: 44 },
    cours: "/courses/equity?module=6",
    calculs: [
      {
        cle: "market-share-hhi",
        nom: "Taille de marché, part de marché et HHI",
        href: "/calculs/equity/market-share-hhi",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=6", page: 6 }],
    flashcards: [],
  },
  {
    id: "equity:7",
    matiere: "equity",
    lm: 7,
    titre: "Company Analysis: Forecasting",
    court: "Prévisions d'entreprise",
    readings: { banque: 47, schweser: 45 },
    cours: "/courses/equity?module=7",
    calculs: [
      {
        cle: "forecasting",
        nom: "Prévisions : CA, marge brute et BFR",
        href: "/calculs/equity/forecasting",
      },
    ],
    fiches: [{ href: "/fiches/equity?page=5", page: 5 }],
    flashcards: [],
  },
  {
    id: "equity:8",
    matiere: "equity",
    lm: 8,
    titre: "Equity Valuation: Concepts and Basic Tools",
    court: "Valorisation des actions",
    readings: { banque: 48, schweser: 46 },
    cours: "/courses/equity?module=8",
    calculs: [
      {
        cle: "ddm-holding-period",
        nom: "DDM sur horizon de détention (holding period)",
        href: "/calculs/equity/ddm-holding-period",
      },
      { cle: "fcfe", nom: "FCFE et valorisation par le FCFE", href: "/calculs/equity/fcfe" },
      {
        cle: "required-return",
        nom: "Rendement exigé et rendement attendu d'une action",
        href: "/calculs/equity/required-return",
      },
      {
        cle: "preferred-stock",
        nom: "Actions de préférence (preferred stock)",
        href: "/calculs/equity/preferred-stock",
      },
      {
        cle: "gordon-growth",
        nom: "Modèle de Gordon (constant growth DDM)",
        href: "/calculs/equity/gordon-growth",
      },
      {
        cle: "sustainable-growth",
        nom: "Croissance soutenable g = b × ROE",
        href: "/calculs/equity/sustainable-growth",
      },
      {
        cle: "multistage-ddm",
        nom: "DDM multi-étapes (multistage)",
        href: "/calculs/equity/multistage-ddm",
      },
      {
        cle: "justified-pe",
        nom: "P/E justifié (justified leading / trailing P/E)",
        href: "/calculs/equity/justified-pe",
      },
      {
        cle: "price-multiples",
        nom: "Multiples de prix : P/E, P/B, P/S, P/CF",
        href: "/calculs/equity/price-multiples",
      },
      { cle: "ev-ebitda", nom: "Enterprise value et EV/EBITDA", href: "/calculs/equity/ev-ebitda" },
    ],
    fiches: [{ href: "/fiches/equity?page=7", page: 7 }, { href: "/fiches/equity?page=8", page: 8 }],
    flashcards: [],
  },
  {
    id: "fixed_income:1",
    matiere: "fixed_income",
    lm: 1,
    titre: "Fixed-Income Instrument Features",
    court: "Caractéristiques des obligations",
    readings: { banque: 49, schweser: 47 },
    cours: "/courses/fixed-income?module=1",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=1", page: 1 }],
    flashcards: [],
  },
  {
    id: "fixed_income:2",
    matiere: "fixed_income",
    lm: 2,
    titre: "Fixed-Income Cash Flows and Types",
    court: "Flux et types d'obligations",
    readings: { banque: 50, schweser: 48 },
    cours: "/courses/fixed-income?module=2",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=1", page: 1 },
      { href: "/fiches/fixed-income?page=7", page: 7 },
      { href: "/fiches/fixed-income?page=2", page: 2 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:3",
    matiere: "fixed_income",
    lm: 3,
    titre: "Fixed-Income Issuance and Trading",
    court: "Émission et négociation",
    readings: { banque: 51, schweser: 49 },
    cours: "/courses/fixed-income?module=3",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=2", page: 2 }],
    flashcards: [],
  },
  {
    id: "fixed_income:4",
    matiere: "fixed_income",
    lm: 4,
    titre: "Fixed-Income Markets for Corporate Issuers",
    court: "Dette des entreprises",
    readings: { banque: 52, schweser: 50 },
    cours: "/courses/fixed-income?module=4",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=2", page: 2 }],
    flashcards: [],
  },
  {
    id: "fixed_income:5",
    matiere: "fixed_income",
    lm: 5,
    titre: "Fixed-Income Markets for Government Issuers",
    court: "Dette publique",
    readings: { banque: 53, schweser: 51 },
    cours: "/courses/fixed-income?module=5",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=2", page: 2 }],
    flashcards: [],
  },
  {
    id: "fixed_income:6",
    matiere: "fixed_income",
    lm: 6,
    titre: "Fixed-Income Bond Valuation: Prices and Yields",
    court: "Prix et rendement",
    readings: { banque: 54, schweser: 52 },
    cours: "/courses/fixed-income?module=6",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=1", page: 1 }],
    flashcards: [],
  },
  {
    id: "fixed_income:7",
    matiere: "fixed_income",
    lm: 7,
    titre: "Yield and Yield Spread Measures for Fixed-Rate Bonds",
    court: "Rendements et spreads (taux fixe)",
    readings: { banque: 55, schweser: 53 },
    cours: "/courses/fixed-income?module=7",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=3", page: 3 },
      { href: "/fiches/fixed-income?page=1", page: 1 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:8",
    matiere: "fixed_income",
    lm: 8,
    titre: "Yield and Yield Spread Measures for Floating-Rate Instruments",
    court: "Taux variables et marché monétaire",
    readings: { banque: 56, schweser: 54 },
    cours: "/courses/fixed-income?module=8",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=3", page: 3 }],
    flashcards: [],
  },
  {
    id: "fixed_income:9",
    matiere: "fixed_income",
    lm: 9,
    titre: "The Term Structure of Interest Rates: Spot, Par, and Forward Curves",
    court: "Courbe des taux",
    readings: { banque: 57, schweser: 55 },
    cours: "/courses/fixed-income?module=9",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=3", page: 3 }],
    flashcards: [],
  },
  {
    id: "fixed_income:10",
    matiere: "fixed_income",
    lm: 10,
    titre: "Interest Rate Risk and Return",
    court: "Risque de taux",
    readings: { banque: 58, schweser: 56 },
    cours: "/courses/fixed-income?module=10",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=4", page: 4 }],
    flashcards: [],
  },
  {
    id: "fixed_income:11",
    matiere: "fixed_income",
    lm: 11,
    titre: "Yield-Based Bond Duration Measures and Properties",
    court: "Duration",
    readings: { banque: 59, schweser: 57 },
    cours: "/courses/fixed-income?module=11",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=4", page: 4 },
      { href: "/fiches/fixed-income?page=5", page: 5 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:12",
    matiere: "fixed_income",
    lm: 12,
    titre: "Yield-Based Bond Convexity and Portfolio Properties",
    court: "Convexité",
    readings: { banque: 60, schweser: 58 },
    cours: "/courses/fixed-income?module=12",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=4", page: 4 }],
    flashcards: [],
  },
  {
    id: "fixed_income:13",
    matiere: "fixed_income",
    lm: 13,
    titre: "Curve-Based and Empirical Fixed-Income Risk Measures",
    court: "Duration effective et empirique",
    readings: { banque: 61, schweser: 59 },
    cours: "/courses/fixed-income?module=13",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=4", page: 4 },
      { href: "/fiches/fixed-income?page=5", page: 5 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:14",
    matiere: "fixed_income",
    lm: 14,
    titre: "Credit Risk",
    court: "Risque de crédit",
    readings: { banque: 62, schweser: 60 },
    cours: "/courses/fixed-income?module=14",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=5", page: 5 }],
    flashcards: [],
  },
  {
    id: "fixed_income:15",
    matiere: "fixed_income",
    lm: 15,
    titre: "Credit Analysis for Government Issuers",
    court: "Crédit des émetteurs publics",
    readings: { banque: 63, schweser: 61 },
    cours: "/courses/fixed-income?module=15",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=5", page: 5 },
      { href: "/fiches/fixed-income?page=2", page: 2 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:16",
    matiere: "fixed_income",
    lm: 16,
    titre: "Credit Analysis for Corporate Issuers",
    court: "Crédit des entreprises",
    readings: { banque: 64, schweser: 62 },
    cours: "/courses/fixed-income?module=16",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=6", page: 6 },
      { href: "/fiches/fixed-income?page=5", page: 5 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:17",
    matiere: "fixed_income",
    lm: 17,
    titre: "Fixed-Income Securitization",
    court: "Titrisation",
    readings: { banque: 65, schweser: 63 },
    cours: "/courses/fixed-income?module=17",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=7", page: 7 }],
    flashcards: [],
  },
  {
    id: "fixed_income:18",
    matiere: "fixed_income",
    lm: 18,
    titre: "Asset-Backed Security (ABS) Instrument and Market Features",
    court: "ABS",
    readings: { banque: 66, schweser: 64 },
    cours: "/courses/fixed-income?module=18",
    calculs: [],
    fiches: [
      { href: "/fiches/fixed-income?page=7", page: 7 },
      { href: "/fiches/fixed-income?page=8", page: 8 },
    ],
    flashcards: [],
  },
  {
    id: "fixed_income:19",
    matiere: "fixed_income",
    lm: 19,
    titre: "Mortgage-Backed Security (MBS) Instrument and Market Features",
    court: "MBS",
    readings: { banque: 67, schweser: 65 },
    cours: "/courses/fixed-income?module=19",
    calculs: [],
    fiches: [{ href: "/fiches/fixed-income?page=8", page: 8 }],
    flashcards: [],
  },
  {
    id: "derivatives:1",
    matiere: "derivatives",
    lm: 1,
    titre: "Derivative Instrument and Derivative Market Features",
    court: "Marchés dérivés",
    readings: { banque: 68, schweser: 66 },
    cours: "/courses/derivatives?module=1",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r66", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:2",
    matiere: "derivatives",
    lm: 2,
    titre: "Forward Commitment and Contingent Claim Features and Instruments",
    court: "Engagements fermes et droits conditionnels",
    readings: { banque: 69, schweser: 67 },
    cours: "/courses/derivatives?module=2",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r67", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:3",
    matiere: "derivatives",
    lm: 3,
    titre: "Derivative Benefits, Risks, and Issuer and Investor Uses",
    court: "Avantages, risques et usages des dérivés",
    readings: { banque: 70, schweser: 68 },
    cours: "/courses/derivatives?module=3",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r68", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:4",
    matiere: "derivatives",
    lm: 4,
    titre: "Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives",
    court: "Arbitrage et coût de portage",
    readings: { banque: 71, schweser: 69 },
    cours: "/courses/derivatives?module=4",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r69", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:5",
    matiere: "derivatives",
    lm: 5,
    titre: "Pricing and Valuation of Forward Contracts and for an Underlying with Varying Maturities",
    court: "Forwards",
    readings: { banque: 72, schweser: 70 },
    cours: "/courses/derivatives?module=5",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r70", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:6",
    matiere: "derivatives",
    lm: 6,
    titre: "Pricing and Valuation of Futures Contracts",
    court: "Futures",
    readings: { banque: 73, schweser: 71 },
    cours: "/courses/derivatives?module=6",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r71", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:7",
    matiere: "derivatives",
    lm: 7,
    titre: "Pricing and Valuation of Interest Rate and Other Swaps",
    court: "Swaps",
    readings: { banque: 74, schweser: 72 },
    cours: "/courses/derivatives?module=7",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r72", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:8",
    matiere: "derivatives",
    lm: 8,
    titre: "Pricing and Valuation of Options",
    court: "Options",
    readings: { banque: 75, schweser: 73 },
    cours: "/courses/derivatives?module=8",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r73", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:9",
    matiere: "derivatives",
    lm: 9,
    titre: "Option Replication Using Put–Call Parity",
    court: "Parité put-call",
    readings: { banque: 76, schweser: 74 },
    cours: "/courses/derivatives?module=9",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r74", page: null }],
    flashcards: [],
  },
  {
    id: "derivatives:10",
    matiere: "derivatives",
    lm: 10,
    titre: "Valuing a Derivative Using a One-Period Binomial Model",
    court: "Modèle binomial",
    readings: { banque: 77, schweser: 75 },
    cours: "/courses/derivatives?module=10",
    calculs: [],
    fiches: [{ href: "/fiches/derivatives#r75", page: null }],
    flashcards: [],
  },
  {
    id: "alternatives:1",
    matiere: "alternatives",
    lm: 1,
    titre: "Alternative Investment Features, Methods, and Structures",
    court: "Structures des alternatifs",
    readings: { banque: 78, schweser: 76 },
    cours: "/courses/alternative-investments?module=1",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:2",
    matiere: "alternatives",
    lm: 2,
    titre: "Alternative Investment Performance and Returns",
    court: "Rendements et frais des alternatifs",
    readings: { banque: 79, schweser: 77 },
    cours: "/courses/alternative-investments?module=2",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:3",
    matiere: "alternatives",
    lm: 3,
    titre: "Investments in Private Capital: Equity and Debt",
    court: "Private equity et dette privée",
    readings: { banque: 80, schweser: 78 },
    cours: "/courses/alternative-investments?module=3",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:4",
    matiere: "alternatives",
    lm: 4,
    titre: "Real Estate and Infrastructure",
    court: "Immobilier et infrastructures",
    readings: { banque: 81, schweser: 79 },
    cours: "/courses/alternative-investments?module=4",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:5",
    matiere: "alternatives",
    lm: 5,
    titre: "Natural Resources",
    court: "Ressources naturelles",
    readings: { banque: 82, schweser: 80 },
    cours: "/courses/alternative-investments?module=5",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:6",
    matiere: "alternatives",
    lm: 6,
    titre: "Hedge Funds",
    court: "Hedge funds",
    readings: { banque: 83, schweser: 81 },
    cours: "/courses/alternative-investments?module=6",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "alternatives:7",
    matiere: "alternatives",
    lm: 7,
    titre: "Introduction to Digital Assets",
    court: "Actifs numériques",
    readings: { banque: 84, schweser: 82 },
    cours: "/courses/alternative-investments?module=7",
    calculs: [],
    fiches: [],
    flashcards: [],
  },
  {
    id: "portfolio:1",
    matiere: "portfolio",
    lm: 1,
    titre: "Portfolio Risk and Return: Part I",
    court: "Risque et diversification",
    readings: { banque: 20, schweser: 83 },
    cours: "/courses/portfolio-management?module=1",
    calculs: [
      {
        cle: "historical-stats",
        nom: "Moyenne, variance et écart-type historiques",
        href: "/calculs/portfolio-management/historical-stats",
      },
      {
        cle: "covariance-correlation",
        nom: "Covariance et corrélation",
        href: "/calculs/portfolio-management/covariance-correlation",
      },
      {
        cle: "two-asset-portfolio",
        nom: "Portefeuille à 2 actifs : rendement et écart-type",
        href: "/calculs/portfolio-management/two-asset-portfolio",
      },
      {
        cle: "diversification",
        nom: "Corrélation et diversification (ρ = ±1, ratio de diversification)",
        href: "/calculs/portfolio-management/diversification",
      },
      {
        cle: "utility",
        nom: "Utilité et aversion au risque (U = E(R) − ½Aσ²)",
        href: "/calculs/portfolio-management/utility",
      },
    ],
    fiches: [{ href: "/fiches/portfolio-management?page=1", page: 1 }],
    flashcards: [],
  },
  {
    id: "portfolio:2",
    matiere: "portfolio",
    lm: 2,
    titre: "Portfolio Risk and Return: Part II",
    court: "CAPM et bêta",
    readings: { banque: 21, schweser: 84 },
    cours: "/courses/portfolio-management?module=2",
    calculs: [
      {
        cle: "capital-allocation-line",
        nom: "Actif sans risque + portefeuille risqué (CAL)",
        href: "/calculs/portfolio-management/capital-allocation-line",
      },
      {
        cle: "capital-market-line",
        nom: "Capital market line (CML)",
        href: "/calculs/portfolio-management/capital-market-line",
      },
      {
        cle: "systematic-risk",
        nom: "Risque systématique et spécifique",
        href: "/calculs/portfolio-management/systematic-risk",
      },
      {
        cle: "return-generating-models",
        nom: "Market model et modèles multifactoriels (return generating models)",
        href: "/calculs/portfolio-management/return-generating-models",
      },
      {
        cle: "beta",
        nom: "Bêta (β = Cov / σM² = ρ σi / σM)",
        href: "/calculs/portfolio-management/beta",
      },
      {
        cle: "portfolio-beta",
        nom: "Bêta de portefeuille",
        href: "/calculs/portfolio-management/portfolio-beta",
      },
      { cle: "capm", nom: "CAPM : rendement exigé", href: "/calculs/portfolio-management/capm" },
      {
        cle: "sml-valuation",
        nom: "SML : titre sur- ou sous-évalué",
        href: "/calculs/portfolio-management/sml-valuation",
      },
      {
        cle: "sharpe-ratio",
        nom: "Ratio de Sharpe",
        href: "/calculs/portfolio-management/sharpe-ratio",
      },
      {
        cle: "treynor-measure",
        nom: "Ratio de Treynor",
        href: "/calculs/portfolio-management/treynor-measure",
      },
      {
        cle: "m-squared",
        nom: "M² (M-squared) et M² alpha",
        href: "/calculs/portfolio-management/m-squared",
      },
      {
        cle: "jensens-alpha",
        nom: "Alpha de Jensen",
        href: "/calculs/portfolio-management/jensens-alpha",
      },
    ],
    fiches: [{ href: "/fiches/portfolio-management?page=2", page: 2 }],
    flashcards: [],
  },
  {
    id: "portfolio:3",
    matiere: "portfolio",
    lm: 3,
    titre: "Portfolio Management: An Overview",
    court: "Processus de gestion",
    readings: { banque: 85, schweser: 85 },
    cours: "/courses/portfolio-management?module=3",
    calculs: [],
    fiches: [{ href: "/fiches/portfolio-management?page=3", page: 3 }],
    flashcards: [],
  },
  {
    id: "portfolio:4",
    matiere: "portfolio",
    lm: 4,
    titre: "Basics of Portfolio Planning and Construction",
    court: "IPS et allocation",
    readings: { banque: 86, schweser: 86 },
    cours: "/courses/portfolio-management?module=4",
    calculs: [],
    fiches: [{ href: "/fiches/portfolio-management?page=4", page: 4 }],
    flashcards: [],
  },
  {
    id: "portfolio:5",
    matiere: "portfolio",
    lm: 5,
    titre: "The Behavioral Biases of Individuals",
    court: "Biais comportementaux",
    readings: { banque: 87, schweser: 87 },
    cours: "/courses/portfolio-management?module=5",
    calculs: [],
    fiches: [{ href: "/fiches/portfolio-management?page=5", page: 5 }],
    flashcards: [],
  },
  {
    id: "portfolio:6",
    matiere: "portfolio",
    lm: 6,
    titre: "Introduction to Risk Management",
    court: "Gestion des risques",
    readings: { banque: 88, schweser: 88 },
    cours: "/courses/portfolio-management?module=6",
    calculs: [],
    fiches: [{ href: "/fiches/portfolio-management?page=6", page: 6 }],
    flashcards: [],
  },
];

const PAR_ID = new Map(NOTIONS.map((n) => [n.id, n]));
const PAR_READING: Record<Numerotation, Map<number, Notion>> = {
  banque: new Map(NOTIONS.map((n) => [n.readings.banque, n])),
  schweser: new Map(NOTIONS.map((n) => [n.readings.schweser, n])),
};

/** Les anciens titres de séries qui suivent la numérotation Schweser. */
const TITRES_SCHWESER = new Set([
  "Fixed-Income Instruments & Markets — QCM (R47–R51)",
  "Bond Valuation & Yield Measures — QCM (R52–R54)",
  "Term Structure of Interest Rates — QCM (R55)",
  "Interest Rate Risk: Duration & Convexity — QCM (R56–R59)",
  "Credit Analysis — QCM (R60–R62)",
  "Securitization, ABS & MBS — QCM (R63–R65)",
  "Fixed-Income Instruments & Markets (R47–R51)",
  "Bond Valuation & Yield Measures (R52–R54)",
  "Term Structure of Interest Rates (R55)",
  "Interest Rate Risk: Duration & Convexity (R56–R59)",
  "Credit Analysis (R60–R62)",
  "Securitization, ABS & MBS (R63–R65)",
]);

export function notionParId(id: string | null | undefined): Notion | null {
  return id ? PAR_ID.get(id) ?? null : null;
}

export function notionsDeMatiere(matiere: string): Notion[] {
  return NOTIONS.filter((n) => n.matiere === matiere);
}

/** La notion d'un reading (« 59 », 91.3 → LM « Guidance for Standards I–VII »). */
export function notionParReading(reading: number | string, numerotation: Numerotation = "banque"): Notion | null {
  return PAR_READING[numerotation].get(Math.floor(Number(reading))) ?? null;
}

function numerotationDuTitre(titre: string): Numerotation {
  return TITRES_SCHWESER.has(titre) ? "schweser" : "banque";
}

/** Les readings d'un titre « … (R59–R61) », « … (R45, R47) », « … (R91.3–R91.5) » (parties entières). */
function readingsDuTitre(titre: string): number[] {
  const m = /\(((?:R[0-9.]+(?:–R[0-9.]+)?)(?:, R[0-9.]+(?:–R[0-9.]+)?)*)\)\s*$/.exec(titre);
  if (!m) return [];
  const out = new Set<number>();
  for (const morceau of m[1].split(", ")) {
    const [a, b] = morceau.split("–").map((x) => Math.floor(Number(x.replace(/^R/, ""))));
    for (let i = a; i <= (b ?? a); i++) out.add(i);
  }
  return [...out];
}

/** Les notions d'une série d'après son titre, dans la bonne numérotation (vide si le titre n'a pas de plage R). */
export function notionsDuTitre(titre: string): Notion[] {
  const numerotation = numerotationDuTitre(titre);
  const out: Notion[] = [];
  for (const r of readingsDuTitre(titre)) {
    const n = notionParReading(r, numerotation);
    if (n && !out.includes(n)) out.push(n);
  }
  return out;
}
